// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKfVSAcmKWYeh57ltmeHXup1u80aigX2s',
    appId: '1:151757927956:web:1386b3c539ea9490fe1901',
    messagingSenderId: '151757927956',
    projectId: 'project-identis',
    authDomain: 'project-identis.firebaseapp.com',
    storageBucket: 'project-identis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7DwrXLX-7h-3NL8DwLb0AZ84YXnEsGUI',
    appId: '1:151757927956:android:adb6b6a0b2ee069afe1901',
    messagingSenderId: '151757927956',
    projectId: 'project-identis',
    storageBucket: 'project-identis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAob2GLBqsduw0wB60GFRx3k-4f0YMWgrs',
    appId: '1:151757927956:ios:2d91cfdc703c841efe1901',
    messagingSenderId: '151757927956',
    projectId: 'project-identis',
    storageBucket: 'project-identis.firebasestorage.app',
    iosBundleId: 'com.example.identisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAob2GLBqsduw0wB60GFRx3k-4f0YMWgrs',
    appId: '1:151757927956:ios:2d91cfdc703c841efe1901',
    messagingSenderId: '151757927956',
    projectId: 'project-identis',
    storageBucket: 'project-identis.firebasestorage.app',
    iosBundleId: 'com.example.identisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKfVSAcmKWYeh57ltmeHXup1u80aigX2s',
    appId: '1:151757927956:web:dde9a51486d55811fe1901',
    messagingSenderId: '151757927956',
    projectId: 'project-identis',
    authDomain: 'project-identis.firebaseapp.com',
    storageBucket: 'project-identis.firebasestorage.app',
  );
}
